---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/A2/A2.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/249376/articles/335447/master/file/figures/A2/A2.png"
    folder_url: "/users/249376/articles/335447/master/folder/figures/A2"
